package a.a.a;

import mod.jbk.build.BuiltInLibraries;

/**
 * An object representing a built-in library, e.g. the MDC library (nicknamed material-1.0.0)
 */
public class Jp {

    /**
     * The library's name inside libs.zip or dexs.zip, e.g. material-1.0.0
     */
    public String a;
    /**
     * The library's base package name, e.g. com.google.android.material
     */
    public String b = "";
    /**
     * Indicator for the library having resources that need constants in an R class generated by a resource processor
     */
    public boolean c;
    /**
     * Indicator for the library having assets that need to be added to the APK
     */
    public boolean d;

    public Jp(String libraryName) {
        a = libraryName;
        c = BuiltInLibraryUtils.hasResources(libraryName);
        d = libraryName.equals(BuiltInLibraries.CODE_VIEW);
        if (c || d) {
            b = BuiltInLibraryUtils.getPackageName(libraryName);
        }
    }

    /**
     * @return The library's name inside libs.zip or dexs.zip, e.g. material-1.0.0
     * @see Jp#a
     */
    public String a() {
        return a;
    }

    /**
     * @return The library's base package name, e.g. com.google.android.material
     * @see Jp#b
     */
    public String b() {
        return b;
    }

    /**
     * @return <code>true</code> if the library has resources that need constants in an R class,
     * <code>false</code> otherwise
     * @see Jp#c
     */
    public boolean c() {
        return c;
    }

    /**
     * @return <code>true</code> if the library has assets that need to be put into the APK,
     * <code>false</code> otherwise
     * @see Jp#d
     */
    public boolean d() {
        return d;
    }
}
