package a.a.a;

import android.content.Context;
import android.util.Log;
import android.util.Pair;

import androidx.core.content.ContextCompat;

import com.besome.sketch.SketchApplication;
import com.besome.sketch.beans.BlockBean;
import com.besome.sketch.beans.ComponentBean;
import com.besome.sketch.beans.ProjectFileBean;
import com.besome.sketch.beans.ProjectLibraryBean;
import com.besome.sketch.beans.SrcCodeBean;
import com.sketchware.remod.R;

import java.io.File;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import mod.agus.jcoderz.lib.FileUtil;
import mod.hey.studios.build.BuildSettings;
import mod.hey.studios.project.ProjectSettings;
import mod.hilal.saif.blocks.CommandBlock;

public class yq {

    /**
     * Firebase Database storage location RegExp matcher to remove unwanted parts of storage URL
     * to get the actual project ID.
     * <p/>
     * Users should enter the entire storage URL without <code>https://</code> at the beginning and
     * <code>/</code> at the end, e.g. <code>sk-pro-default-rtdb.firebaseio.com</code>.
     */
    private static final String FIREBASE_DATABASE_STORAGE_LOCATION_MATCHER = "(-default-rtdb)?\\.[a-z](.?)+";

    /**
     * Example content: /storage/emulated/0/.sketchware/mysc/605/app/src/main/assets
     */
    public final String assetsPath;

    /**
     * Example content: /storage/emulated/0/.sketchware/mysc/605/app/src/main/assets/fonts
     */
    public final String fontsPath;

    /**
     * Path of ZIP file containing compiled resources of the current project,
     * e.g. /storage/emulated/0/.sketchware/mysc/605/bin/InternalDemo.apk.res
     */
    public final String resourcesApkPath;

    /**
     * Example content: /storage/emulated/0/.sketchware/mysc/605/bin/classes.dex
     */
    public final String classesDexPath;

    /**
     * Example content: /storage/emulated/0/.sketchware/mysc/605/bin/InternalDemo.apk.unsigned
     */
    public final String unsignedUnalignedApkPath;

    /**
     * Example content: /storage/emulated/0/.sketchware/mysc/605/bin/InternalDemo.apk
     */
    public final String finalToInstallApkPath;

    /**
     * Example content: /storage/emulated/0/sketchware/signed_apk/InternalDemo_release.apk
     */
    public final String releaseApkPath;

    private final oB fileUtil;
    public jq N;
    public final Zo O;

    /**
     * Path of file with ProGuard rules automatically generated by aapt2,
     * e.g. /storage/emulated/0/.sketchware/mysc/605/bin/aapt_rules.pro
     */
    public final String aaptProGuardRules;

    /**
     * Example content: /storage/emulated/0/.sketchware/mysc/605/bin/InternalDemo.apk.unsigned.aligned
     */
    public final String unsignedAlignedApkPath;

    public final String sc_id;

    /**
     * Example content: /storage/emulated/0/.sketchware/mysc/605/
     */
    public final String projectMyscPath;

    /**
     * ProGuarded classes.jar file's path of current project,
     * e.g. /storage/emulated/0/.sketchware/mysc/605/bin/classes_proguard.jar
     */
    public final String classesProGuardPath;

    public final String projectName;

    public final String packageName;

    public final String applicationName;

    public final int colorAccent;

    public final int colorPrimary;

    public final int colorPrimaryDark;

    public final int colorControlHighlight;

    public final int colorControlNormal;

    public final String versionCode;

    public final String versionName;

    /**
     * Package name of current project,
     * but "folders" separated with slashes (/) instead of periods (.),
     * e.g. com/jbk/internal/demo
     */
    public final String packageNameAsFolders;

    /**
     * Path of file containing the ProGuard mapping,
     * e.g. /storage/emulated/0/.sketchware/mysc/605/bin/mapping.txt
     */
    public final String proGuardMappingPath;

    /**
     * Path of file containing ProGuard seeds,
     * e.g. /storage/emulated/0/.sketchware/mysc/605/bin/seeds.txt
     */
    public final String proGuardSeedsPath;

    /**
     * Path of file containing ProGuard usage,
     * e.g. /storage/emulated/0/.sketchware/mysc/605/bin/usage.txt
     */
    public final String proGuardUsagePath;

    /**
     * Current project's ProjectSettings object
     */
    public final ProjectSettings projectSettings;

    /**
     * Example content: /storage/emulated/0/.sketchware/mysc/605/app/src/main/AndroidManifest.xml
     */
    public final String androidManifestPath;

    /**
     * Path of ProGuard rules auto-generated to exclude built-in libraries and non-Full Mode Local libraries,
     * e.g. /storage/emulated/0/.sketchware/mysc/605/bin/rules_generated.pro
     */
    public final String proGuardAutoGeneratedExclusions;

    /**
     * Example content: /storage/emulated/0/.sketchware/mysc/605/app/src/main
     */
    public final String generatedFilesPath;

    /**
     * Example content: /storage/emulated/0/.sketchware/mysc/605/bin
     */
    public final String binDirectoryPath;

    /**
     * Example content: /storage/emulated/0/.sketchware/mysc/605/bin/classes
     */
    public final String compiledClassesPath;

    /**
     * Path of the unaligned but signed APK,
     * e.g. /storage/emulated/0/.sketchware/mysc/605/bin/InternalDemo.apk.signed.unaligned
     */
    public final String unalignedSignedApkPath;

    /**
     * Project's generated R.java files directory,
     * e.g. /storage/emulated/0/.sketchware/mysc/605/gen
     */
    public final String rJavaDirectoryPath;

    /**
     * Example content: /storage/emulated/0/.sketchware/mysc/605/app/src/main/res
     */
    public final String resDirectoryPath;

    /**
     * Example content: /storage/emulated/0/.sketchware/mysc/605/app/src/main/res/layout
     */
    public final String layoutFilesPath;

    /**
     * Example content: /storage/emulated/0/.sketchware/mysc/605/app/src/main/java
     */
    public final String javaFilesPath;

    /**
     * Example content: /storage/emulated/0/.sketchware/mysc/605/app/src/main/res/raw
     */
    public final String importedSoundsPath;

    public yq(Context context, String sc_id) {
        this(context, wq.d(sc_id), lC.b(sc_id));
    }

    public yq(Context context, String myscFolderPath, HashMap<String, Object> metadata) {
        N = new jq();
        sc_id = yB.c(metadata, "sc_id");
        projectMyscPath = myscFolderPath.endsWith(File.separator) ? myscFolderPath : myscFolderPath + File.separator;
        packageName = yB.c(metadata, "my_sc_pkg_name");
        projectName = yB.c(metadata, "my_ws_name");
        applicationName = yB.c(metadata, "my_app_name");
        versionCode = yB.c(metadata, "sc_ver_code");
        versionName = yB.c(metadata, "sc_ver_name");

        colorAccent = yB.a(metadata, "color_accent", ContextCompat.getColor(context, R.color.color_accent));
        colorPrimary = yB.a(metadata, "color_primary", ContextCompat.getColor(context, R.color.color_primary));
        colorPrimaryDark = yB.a(metadata, "color_primary_dark", ContextCompat.getColor(context, R.color.color_primary_dark));
        colorControlHighlight = yB.a(metadata, "color_control_highlight", ContextCompat.getColor(context, R.color.color_control_highlight));
        colorControlNormal = yB.a(metadata, "color_control_normal", ContextCompat.getColor(context, R.color.color_control_normal));
        projectSettings = new ProjectSettings(sc_id);

        fileUtil = new oB(true);
        O = new Zo(context);
        packageNameAsFolders = packageName.replaceAll("\\.", File.separator);
        binDirectoryPath = projectMyscPath + "bin";
        compiledClassesPath = binDirectoryPath + File.separator + "classes";
        classesProGuardPath = binDirectoryPath + File.separator + "classes_proguard.jar";
        aaptProGuardRules = binDirectoryPath + File.separator + "aapt_rules.pro";
        proGuardSeedsPath = binDirectoryPath + File.separator + "seeds.txt";
        proGuardUsagePath = binDirectoryPath + File.separator + "usage.txt";
        proGuardMappingPath = binDirectoryPath + File.separator + "mapping.txt";
        proGuardAutoGeneratedExclusions = binDirectoryPath + File.separator + "rules_generated.pro";
        rJavaDirectoryPath = projectMyscPath + "gen";
        generatedFilesPath = projectMyscPath + "app" + File.separator + "src" + File.separator + "main";
        javaFilesPath = generatedFilesPath + File.separator + "java";
        resDirectoryPath = generatedFilesPath + File.separator + "res";
        layoutFilesPath = resDirectoryPath + File.separator + "layout";
        importedSoundsPath = resDirectoryPath + File.separator + "raw";
        assetsPath = generatedFilesPath + File.separator + "assets";
        fontsPath = assetsPath + File.separator + "fonts";
        androidManifestPath = projectMyscPath + "app" + File.separator + "src" + File.separator + "main" + File.separator + "AndroidManifest.xml";
        resourcesApkPath = binDirectoryPath + File.separator + projectName + ".apk.res";
        classesDexPath = binDirectoryPath + File.separator + "classes.dex";
        unsignedUnalignedApkPath = binDirectoryPath + File.separator + projectName + ".apk.unsigned";
        unsignedAlignedApkPath = unsignedUnalignedApkPath + ".aligned";
        unalignedSignedApkPath = binDirectoryPath + File.separator + projectName + ".apk.signed.unaligned";
        finalToInstallApkPath = binDirectoryPath + File.separator + projectName + ".apk";
        releaseApkPath = wq.o() + File.separator + projectName + "_release.apk";
    }

    /**
     * Deletes the directory {@link yq#resDirectoryPath}/values-v21/.
     */
    public void a() {
        File file = new File(resDirectoryPath + File.separator + "values-v21");
        if (file.exists()) {
            fileUtil.a(file);
        }
    }

    /**
     * Creates needed build directories {@link yq#binDirectoryPath}, {@link yq#compiledClassesPath}, {@link yq#rJavaDirectoryPath}, {@link yq#javaFilesPath}, {@link yq#resDirectoryPath},
     * {@link yq#layoutFilesPath}, {@link yq#importedSoundsPath}, {@link yq#assetsPath}, and {@link yq#fontsPath}.
     */
    public void c(Context context) {
        fileUtil.f(binDirectoryPath);
        fileUtil.f(compiledClassesPath);
        fileUtil.f(rJavaDirectoryPath);
        fileUtil.f(javaFilesPath);
        fileUtil.f(resDirectoryPath);
        fileUtil.f(layoutFilesPath);
        fileUtil.f(importedSoundsPath);
        fileUtil.f(assetsPath);
        fileUtil.f(fontsPath);
    }

    /**
     * Prepares to compile and creates /Internal storage/.sketchware/mysc/&lt;sc_id&gt;/ directories,
     * {@link yq#binDirectoryPath}, {@link yq#compiledClassesPath} and {@link yq#rJavaDirectoryPath}.
     */
    public void e() {
        fileUtil.f(binDirectoryPath);
        fileUtil.f(compiledClassesPath);
        fileUtil.f(rJavaDirectoryPath);
    }

    /**
     * Deletes temporary compile cache directories, {@link yq#binDirectoryPath} and {@link yq#rJavaDirectoryPath}. The used method
     * logs all files and folders which get deleted.
     */
    public void f() {
        fileUtil.b(binDirectoryPath);
        fileUtil.b(rJavaDirectoryPath);
    }

    /**
     * Generates top-level build.gradle, build.gradle for module ':app' and settings.gradle files.
     */
    public void h() {
        fileUtil.b(projectMyscPath + File.separator + "app" + File.separator + "build.gradle",
                Lx.a(28, 21, 28, N));
        fileUtil.b(projectMyscPath + File.separator + "settings.gradle", Lx.a());
        fileUtil.b(projectMyscPath + File.separator + "build.gradle", Lx.c("3.4.2", "4.3.3"));
    }

    /**
     * Extracts a ZIP archive from assets to {@link yq#resDirectoryPath}.
     */
    public void a(Context context, String str) {
        try {
            KB.a(context, str, resDirectoryPath);
        } catch (Exception e2) {
            Log.e("ERROR", e2.getMessage(), e2);
        }
    }

    /**
     * Copies a file to the project's app icon path, {@link yq#resDirectoryPath}/drawable-xhdpi/app_icon.png
     */
    public void a(String iconPath) {
        try {
            fileUtil.a(iconPath, resDirectoryPath + File.separator + "drawable-xhdpi" + File.separator + "app_icon.png");
        } catch (Exception e2) {
            e2.printStackTrace();
        }
    }

    /**
     * Generates DebugActivity.java, SketchApplication.java, and SketchLogger.java, if necessary.
     */
    public void a(Context context) {
        boolean logcatEnabled = N.isDebugBuild && new BuildSettings(sc_id).getValue(
                BuildSettings.SETTING_ENABLE_LOGCAT, BuildSettings.SETTING_GENERIC_VALUE_FALSE).equals(BuildSettings.SETTING_GENERIC_VALUE_TRUE);

        String javaDir = FileUtil.getExternalStorageDir() + "/.sketchware/data/" + sc_id + "/files/java/";
        if (!new File(javaDir, "DebugActivity.java").exists()) {
            fileUtil.b(javaFilesPath + File.separator
                            + packageNameAsFolders + File.separator
                            + "DebugActivity.java",
                    fileUtil.b(
                            context,
                            "debug" + File.separator
                                    + "DebugActivity.java"
                    ).replaceAll("<\\?package_name\\?>", packageName));
        }

        if (!new File(javaDir, "SketchApplication.java").exists()) {
            boolean applyMultiDex = projectSettings.getMinSdkVersion() < 21;

            String sketchApplicationFileContent = fileUtil.b(
                    context,
                    "debug" + File.separator + "SketchApplication.java"
            ).replaceAll("<\\?package_name\\?>", packageName);
            if (applyMultiDex) {
                sketchApplicationFileContent = sketchApplicationFileContent.replaceAll(
                        "Application \\{", "androidx.multidex.MultiDexApplication \\{");
            }
            if (logcatEnabled) {
                sketchApplicationFileContent = sketchApplicationFileContent.replace(
                        "super.onCreate();", "SketchLogger.startLogging();\n" +
                                "        super.onCreate();").replace(
                        "Process.killProcess(Process.myPid());",
                        "                SketchLogger.broadcastLog(Log.getStackTraceString(throwable));\n" +
                                "                SketchLogger.stopLogging();\n" + "Process.killProcess(Process.myPid());"
                );
            }

            fileUtil.b(javaFilesPath + File.separator
                            + packageNameAsFolders + File.separator
                            + "SketchApplication.java",
                    sketchApplicationFileContent);
        }

        if (logcatEnabled) {
            if (!new File(javaDir, "SketchLogger.java").exists()) {
                fileUtil.b(javaFilesPath + File.separator
                                + packageNameAsFolders + File.separator
                                + "SketchLogger.java",
                        fileUtil.b(
                                context,
                                "debug" + File.separator
                                        + "SketchLogger.java"
                        ).replaceAll("<\\?package_name\\?>", packageName));
            }
        }
    }

    /**
     * Writes a project file to its correct location. Java files, for example, get saved to
     * <pre>
     *     {@link yq#javaFilesPath} + File.separator + {@link yq#packageNameAsFolders}
     * </pre>, while AndroidManifest.xml gets saved to {@link yq#androidManifestPath}.
     */
    public void a(String fileName, String fileContent) {
        if (fileName.endsWith("java")) {
            fileUtil.b(javaFilesPath + File.separator + packageNameAsFolders + File.separator + fileName, fileContent);
        } else if (fileName.equals("AndroidManifest.xml")) {
            fileUtil.b(androidManifestPath, fileContent);
        } else if (fileName.equals("colors.xml") || fileName.equals("styles.xml") || fileName.equals("strings.xml")) {
            fileUtil.b(resDirectoryPath + File.separator + "values" + File.separator + fileName, fileContent);
        } else if (fileName.equals("provider_paths.xml")) {
            fileUtil.b(resDirectoryPath + File.separator + "xml" + File.separator + fileName, fileContent);
        } else {
            fileUtil.b(layoutFilesPath + File.separator + fileName, fileContent);
        }
    }

    public void a(iC projectLibraryManager, hC projectFileManager, eC projectDataManager, boolean exportingProject) {
        ProjectLibraryBean adMob = projectLibraryManager.b();
        ProjectLibraryBean appCompat = projectLibraryManager.c();
        ProjectLibraryBean firebase = projectLibraryManager.d();
        ProjectLibraryBean googleMaps = projectLibraryManager.e();
        N = new jq();
        N.packageName = packageName;
        N.projectName = applicationName;
        N.versionCode = versionCode;
        N.versionName = versionName;
        N.sc_id = sc_id;
        N.e = O.h();
        N.isDebugBuild = !exportingProject;
        if (firebase.useYn.equals(ProjectLibraryBean.LIB_USE_Y)) {
            N.isFirebaseEnabled = true;
            N.addPermission(jq.PERMISSION_INTERNET);
            N.addPermission(jq.PERMISSION_ACCESS_NETWORK_STATE);
        }
        if (appCompat.useYn.equals(ProjectLibraryBean.LIB_USE_Y)) {
            N.g = true;
        }
        if (adMob.useYn.equals(ProjectLibraryBean.LIB_USE_Y)) {
            N.isAdMobEnabled = true;
            N.addPermission(jq.PERMISSION_INTERNET);
            N.addPermission(jq.PERMISSION_ACCESS_NETWORK_STATE);
            N.setupAdmob(adMob);
        }
        if (googleMaps.useYn.equals(ProjectLibraryBean.LIB_USE_Y)) {
            N.isMapUsed = true;
            N.addPermission(jq.PERMISSION_INTERNET);
            N.addPermission(jq.PERMISSION_ACCESS_NETWORK_STATE);
            N.setupGoogleMap(googleMaps);
        }
        for (ProjectFileBean next : projectFileManager.b()) {
            if (next.hasActivityOption(ProjectFileBean.OPTION_ACTIVITY_DRAWER)) {
                N.a(next.getActivityName()).a = true;
            }
            for (ComponentBean component : projectDataManager.e(next.getJavaName())) {
                N.x.handleComponent(component.type);

                switch (component.type) {
                    case ComponentBean.COMPONENT_TYPE_CAMERA:
                    case 35:
                        N.g = true;
                        N.u = true;
                        N.addPermission(next.getActivityName(), jq.PERMISSION_CAMERA);
                        N.addPermission(next.getActivityName(), jq.PERMISSION_READ_EXTERNAL_STORAGE);
                        N.addPermission(next.getActivityName(), jq.PERMISSION_WRITE_EXTERNAL_STORAGE);
                        break;

                    case ComponentBean.COMPONENT_TYPE_FILE_PICKER:
                        N.addPermission(next.getActivityName(), jq.PERMISSION_READ_EXTERNAL_STORAGE);
                        break;

                    case ComponentBean.COMPONENT_TYPE_FIREBASE:
                        N.isGsonUsed = true;
                        N.isFirebaseDatabaseUsed = true;
                        N.addPermission(next.getActivityName(), jq.PERMISSION_INTERNET);
                        N.addPermission(next.getActivityName(), jq.PERMISSION_ACCESS_NETWORK_STATE);
                        break;

                    case ComponentBean.COMPONENT_TYPE_FIREBASE_STORAGE:
                        N.isFirebaseStorageUsed = true;
                        N.addPermission(next.getActivityName(), jq.PERMISSION_READ_EXTERNAL_STORAGE);
                        N.addPermission(next.getActivityName(), jq.PERMISSION_WRITE_EXTERNAL_STORAGE);
                        break;

                    case ComponentBean.COMPONENT_TYPE_VIBRATOR:
                        N.addPermission(next.getActivityName(), jq.PERMISSION_VIBRATE);
                        break;

                    case ComponentBean.COMPONENT_TYPE_FIREBASE_AUTH:
                        N.isFirebaseAuthUsed = true;
                        N.a(next.getActivityName()).b = true;
                        break;

                    case ComponentBean.COMPONENT_TYPE_REQUEST_NETWORK:
                        N.isGsonUsed = true;
                        N.isHttp3Used = true;
                        N.addPermission(next.getActivityName(), jq.PERMISSION_INTERNET);
                        N.addPermission(next.getActivityName(), jq.PERMISSION_ACCESS_NETWORK_STATE);
                        break;

                    case ComponentBean.COMPONENT_TYPE_SPEECH_TO_TEXT:
                        N.addPermission(next.getActivityName(), jq.PERMISSION_RECORD_AUDIO);
                        break;

                    case ComponentBean.COMPONENT_TYPE_BLUETOOTH_CONNECT:
                        N.addPermission(next.getActivityName(), jq.PERMISSION_BLUETOOTH);
                        N.addPermission(next.getActivityName(), jq.PERMISSION_BLUETOOTH_ADMIN);
                        break;

                    case ComponentBean.COMPONENT_TYPE_LOCATION_MANAGER:
                        N.addPermission(next.getActivityName(), jq.PERMISSION_ACCESS_FINE_LOCATION);
                        break;

                    case ComponentBean.COMPONENT_TYPE_FIREBASE_DYNAMIC_LINKS:
                        N.isDynamicLinkUsed = true;
                        break;

                    default:
                }
            }

            for (Map.Entry<String, ArrayList<BlockBean>> entry : projectDataManager.b(next.getJavaName()).entrySet()) {
                for (BlockBean bean : entry.getValue()) {
                    String opCode = bean.opCode;
                    N.x.setParams(bean.parameters, packageName, opCode);

                    switch (opCode) {
                        case "FirebaseDynamicLink setDataHost":
                        case "setDynamicLinkDataHost":
                            if (bean.parameters.size() >= 2) {
                                N.dlDataList.add(new Pair<>(bean.parameters.get(0), bean.parameters.get(1)));
                            }
                            break;

                        case "setAdmobAppId":
                            N.appId = bean.parameters.get(0);
                            break;

                        case "intentSetAction":
                            // If an Intent setAction (ACTION_CALL) block is used
                            if (bean.parameters.get(1).equals(uq.c[1])) {
                                N.addPermission(next.getActivityName(), jq.PERMISSION_CALL_PHONE);
                            }
                            break;

                        case "fileutilread":
                        case "fileutilisexist":
                        case "fileutillistdir":
                        case "fileutilisdir":
                        case "fileutilisfile":
                        case "fileutillength":
                        case "fileutilStartsWith":
                        case "fileutilEndsWith":
                        case "getJpegRotate":
                        case "setImageFilePath":
                        case "fileutilGetLastSegmentPath":
                            N.addPermission(next.getActivityName(), jq.PERMISSION_READ_EXTERNAL_STORAGE);
                            break;

                        case "fileutilwrite":
                        case "fileutilcopy":
                        case "fileutilcopydir":
                        case "fileutilmove":
                        case "fileutildelete":
                        case "fileutilmakedir":
                        case "resizeBitmapFileRetainRatio":
                        case "resizeBitmapFileToSquare":
                        case "resizeBitmapFileToCircle":
                        case "resizeBitmapFileWithRoundedBorder":
                        case "cropBitmapFileFromCenter":
                        case "rotateBitmapFile":
                        case "scaleBitmapFile":
                        case "skewBitmapFile":
                        case "setBitmapFileColorFilter":
                        case "setBitmapFileBrightness":
                        case "setBitmapFileContrast":
                            N.addPermission(next.getActivityName(), jq.PERMISSION_READ_EXTERNAL_STORAGE);
                            N.addPermission(next.getActivityName(), jq.PERMISSION_WRITE_EXTERNAL_STORAGE);
                            break;

                        case "strToMap":
                        case "mapToStr":
                        case "strToListMap":
                        case "listMapToStr":
                        case "GsonListTojsonString":
                        case "GsonStringToListString":
                        case "GsonStringToListNumber":
                            N.isGsonUsed = true;
                            break;

                        case "setImageUrl":
                            N.isGlideUsed = true;
                            N.addPermission(jq.PERMISSION_INTERNET);
                            break;

                        case "webViewLoadUrl":
                            N.addPermission(jq.PERMISSION_INTERNET);
                            N.addPermission(jq.PERMISSION_ACCESS_NETWORK_STATE);
                            break;

                        default:
                    }
                }
            }
            N.b();
        }
    }

    /**
     * Simply calls {@link yq#b(hC, eC, iC, boolean)} with the same arguments and <code>false</code>.
     *
     * @see yq#b(hC, eC, iC, boolean)
     */
    public void b(hC projectFileManager, eC projectDataManager, iC projectLibraryManager) {
        b(projectFileManager, projectDataManager, projectLibraryManager, false);
    }

    /**
     * Generates the project's files, such as layouts, Java files, but also build.gradle and secrets.xml.
     */
    public void b(hC projectFileManager, eC projectDataManger, iC projectLibraryManager, boolean exportingProject) {
        ArrayList<SrcCodeBean> srcCodeBeans = a(projectFileManager, projectDataManger, projectLibraryManager, exportingProject);
        if (N.u) {
            Nx pathsTag = new Nx("paths");
            pathsTag.a("xmlns", "android", "http://schemas.android.com/apk/res/android");
            Nx externalPathTag = new Nx("external-path");
            externalPathTag.a("", "name", "external_files");
            externalPathTag.a("", "path", ".");
            pathsTag.a(externalPathTag);
            srcCodeBeans.add(new SrcCodeBean("provider_paths.xml",
                    CommandBlock.applyCommands("xml/provider_paths.xml", pathsTag.toCode())));
        }

        for (SrcCodeBean bean : srcCodeBeans) {
            a(bean.srcFileName, bean.source);
        }
        if (N.isFirebaseEnabled || N.isAdMobEnabled || N.isMapUsed) {
            ProjectLibraryBean firebaseLibrary = projectLibraryManager.d();
            Mx mx = new Mx();
            mx.a("google_play_services_version", 12451000);
            if (N.isFirebaseEnabled) {
                mx.a("firebase_database_url", "https://" + firebaseLibrary.data, false);
                mx.a("project_id", firebaseLibrary.data.trim().replaceAll(FIREBASE_DATABASE_STORAGE_LOCATION_MATCHER, ""), false);
                mx.a("google_app_id", firebaseLibrary.reserved1, false);
                if (firebaseLibrary.reserved2 != null && firebaseLibrary.reserved2.length() > 0) {
                    mx.a("google_api_key", firebaseLibrary.reserved2, false);
                }
                if (firebaseLibrary.reserved3 != null && firebaseLibrary.reserved3.length() > 0) {
                    mx.a("google_storage_bucket", firebaseLibrary.reserved3, false);
                }
            }
            if (N.isMapUsed) {
                // if p3 is false, then "translatable="false" will be added
                mx.a("google_maps_key", projectLibraryManager.e().data, false);
            }
            String filePath = "values/secrets.xml";
            fileUtil.b(resDirectoryPath + File.separator + filePath,
                    CommandBlock.applyCommands(filePath, mx.toCode()));
        }
        h();
    }

    /**
     * Get source code files that are viewable in SrcCodeViewer
     */
    public ArrayList<SrcCodeBean> a(hC projectFileManager, eC projectDataManager, iC projectLibraryManager, boolean exportingProject) {
        a(projectLibraryManager, projectFileManager, projectDataManager, exportingProject);
        a(SketchApplication.getContext());
        CommandBlock.x();

        final String javaDir = FileUtil.getExternalStorageDir() + "/.sketchware/data/" + sc_id + "/files/java/";
        final String layoutDir = FileUtil.getExternalStorageDir() + "/.sketchware/data/" + sc_id + "/files/resource/layout/";
        List<File> javaFiles;
        {
            File[] files = new File(javaDir).listFiles();
            if (files == null) files = new File[0];
            javaFiles = Arrays.asList(files);
        }
        List<File> layoutFiles;
        {
            File[] files = new File(layoutDir).listFiles();
            if (files == null) files = new File[0];
            layoutFiles = Arrays.asList(files);
        }

        // Generate Activities unless a custom version of it exists already
        // at /Internal storage/.sketchware/data/<sc_id>/files/java/
        ArrayList<SrcCodeBean> srcCodeBeans = new ArrayList<>();
        for (ProjectFileBean activity : projectFileManager.b()) {
            if (!javaFiles.contains(new File(javaDir + activity.getJavaName()))) {
                srcCodeBeans.add(new SrcCodeBean(activity.getJavaName(),
                        new Jx(N, activity, projectDataManager).generateCode()));
            }
        }

        // Generate layouts unless a custom version of it exists already
        // at /Internal storage/.sketchware/data/<sc_id>/files/resource/layout/
        {
            ArrayList<ProjectFileBean> regularLayouts = projectFileManager.b();
            for (ProjectFileBean layout : regularLayouts) {
                String xmlName = layout.getXmlName();
                Ox ox = new Ox(N, layout);
                ox.a(eC.a(projectDataManager.d(xmlName)), projectDataManager.h(xmlName));
                if (!layoutFiles.contains(new File(layoutDir + xmlName))) {
                    srcCodeBeans.add(new SrcCodeBean(xmlName,
                            CommandBlock.applyCommands(xmlName, ox.b())));
                }
            }
        }
        {
            ArrayList<ProjectFileBean> drawerLayouts = projectFileManager.c();
            for (ProjectFileBean drawerFile : drawerLayouts) {
                String xmlName = drawerFile.getXmlName();
                Ox ox = new Ox(N, drawerFile);
                ox.a(eC.a(projectDataManager.d(xmlName)));
                if (!layoutFiles.contains(new File(layoutDir + xmlName))) {
                    srcCodeBeans.add(new SrcCodeBean(xmlName,
                            CommandBlock.applyCommands(xmlName, ox.b())));
                }
            }
        }

        Ix ix = new Ix(N, projectFileManager.b());
        ix.setYq(this);

        // Make generated classes viewable
        if (!javaFiles.contains(new File(javaDir + "SketchwareUtil.java"))) {
            srcCodeBeans.add(new SrcCodeBean("SketchwareUtil.java",
                    Lx.i(packageName)));
        }

        if (!javaFiles.contains(new File(javaDir + "FileUtil.java"))) {
            srcCodeBeans.add(new SrcCodeBean("FileUtil.java",
                    Lx.e(packageName)));
        }

        if (!javaFiles.contains(new File(javaDir + "RequestNetwork.java")) && N.isHttp3Used) {
            srcCodeBeans.add(new SrcCodeBean("RequestNetwork.java",
                    Lx.j(Lx.h(packageName))));
        }

        if (!FileUtil.isExistFile(javaDir + "RequestNetworkController.java") && N.isHttp3Used) {
            srcCodeBeans.add(new SrcCodeBean("RequestNetworkController.java",
                    Lx.j(Lx.g(packageName))));
        }

        if (!javaFiles.contains(new File(javaDir + "BluetoothConnect.java")) && N.hasPermission(jq.PERMISSION_BLUETOOTH)) {
            srcCodeBeans.add(new SrcCodeBean("BluetoothConnect.java",
                    Lx.j(Lx.b(packageName))));
        }

        if (!javaFiles.contains(new File(javaDir + "BluetoothController.java")) && N.hasPermission(jq.PERMISSION_BLUETOOTH)) {
            srcCodeBeans.add(new SrcCodeBean("BluetoothController.java",
                    Lx.j(Lx.c(packageName))));
        }

        if (N.isMapUsed) {
            if (!javaFiles.contains(new File(javaDir + "GoogleMapController.java")) && N.isMapUsed) {
                srcCodeBeans.add(new SrcCodeBean("GoogleMapController.java",
                        Lx.j(Lx.f(packageName))));
            }
        }

        srcCodeBeans.add(new SrcCodeBean("AndroidManifest.xml",
                CommandBlock.applyCommands("AndroidManifest.xml", ix.a())));
        if (N.g) {
            boolean useNewMaterialComponentsTheme = projectSettings.getValue(ProjectSettings.SETTING_ENABLE_BRIDGELESS_THEMES,
                    BuildSettings.SETTING_GENERIC_VALUE_FALSE).equals(BuildSettings.SETTING_GENERIC_VALUE_TRUE);

            Mx colorsFileBuilder = new Mx();
            colorsFileBuilder.a("colorPrimary", String.format("#%06X", colorPrimary & 0xffffff));
            colorsFileBuilder.a("colorPrimaryDark", String.format("#%06X", colorPrimaryDark & 0xffffff));
            colorsFileBuilder.a("colorAccent", String.format("#%06X", colorAccent & 0xffffff));
            colorsFileBuilder.a("colorControlHighlight", String.format("#%06X", colorControlHighlight & 0xffffff));
            colorsFileBuilder.a("colorControlNormal", String.format("#%06X", colorControlNormal & 0xffffff));
            srcCodeBeans.add(new SrcCodeBean("colors.xml",
                    CommandBlock.applyCommands("colors.xml", colorsFileBuilder.toCode())));

            Mx stylesFileBuilder = new Mx();
            stylesFileBuilder.c("AppTheme", "Theme.MaterialComponents.Light.NoActionBar" + (useNewMaterialComponentsTheme ? "" : ".Bridge"));
            stylesFileBuilder.a("AppTheme", "colorPrimary", "@color/colorPrimary");
            stylesFileBuilder.a("AppTheme", "colorPrimaryDark", "@color/colorPrimaryDark");
            stylesFileBuilder.a("AppTheme", "colorAccent", "@color/colorAccent");
            stylesFileBuilder.a("AppTheme", "colorControlHighlight", "@color/colorControlHighlight");
            stylesFileBuilder.a("AppTheme", "colorControlNormal", "@color/colorControlNormal");
            stylesFileBuilder.c("AppTheme.FullScreen", "AppTheme");
            stylesFileBuilder.a("AppTheme.FullScreen", "android:windowFullscreen", "true");
            stylesFileBuilder.a("AppTheme.FullScreen", "android:windowContentOverlay", "@null");
            stylesFileBuilder.c("AppTheme.AppBarOverlay", "ThemeOverlay.MaterialComponents.Dark.ActionBar");
            stylesFileBuilder.c("AppTheme.PopupOverlay", "ThemeOverlay.MaterialComponents.Light");
            srcCodeBeans.add(new SrcCodeBean("styles.xml",
                    CommandBlock.applyCommands("styles.xml", stylesFileBuilder.toCode())));
        } else {
            Mx stylesFileBuilder = new Mx();
            stylesFileBuilder.c("AppTheme", "@android:style/Theme.Material.Light.DarkActionBar");
            stylesFileBuilder.a("AppTheme", "android:colorPrimary", "@color/colorPrimary");
            stylesFileBuilder.a("AppTheme", "android:colorPrimaryDark", "@color/colorPrimaryDark");
            stylesFileBuilder.a("AppTheme", "android:colorAccent", "@color/colorAccent");
            stylesFileBuilder.a("AppTheme", "android:colorControlHighlight", "@color/colorControlHighlight");
            stylesFileBuilder.a("AppTheme", "android:colorControlNormal", "@color/colorControlNormal");
            stylesFileBuilder.c("FullScreen", "@android:style/Theme.Material.Light.NoActionBar.Fullscreen");
            stylesFileBuilder.a("FullScreen", "android:colorPrimary", "@color/colorPrimary");
            stylesFileBuilder.a("FullScreen", "android:colorPrimaryDark", "@color/colorPrimaryDark");
            stylesFileBuilder.a("FullScreen", "android:colorAccent", "@color/colorAccent");
            stylesFileBuilder.a("FullScreen", "android:colorControlHighlight", "@color/colorControlHighlight");
            stylesFileBuilder.a("FullScreen", "android:colorControlNormal", "@color/colorControlNormal");
            stylesFileBuilder.c("NoActionBar", "@android:style/Theme.Material.Light.NoActionBar");
            stylesFileBuilder.a("NoActionBar", "android:colorPrimary", "@color/colorPrimary");
            stylesFileBuilder.a("NoActionBar", "android:colorPrimaryDark", "@color/colorPrimaryDark");
            stylesFileBuilder.a("NoActionBar", "android:colorAccent", "@color/colorAccent");
            stylesFileBuilder.a("NoActionBar", "android:colorControlHighlight", "@color/colorControlHighlight");
            stylesFileBuilder.a("NoActionBar", "android:colorControlNormal", "@color/colorControlNormal");
            stylesFileBuilder.c("NoStatusBar", "AppTheme");
            stylesFileBuilder.a("NoStatusBar", "android:windowFullscreen", "true");
            srcCodeBeans.add(new SrcCodeBean("styles.xml",
                    CommandBlock.applyCommands("styles.xml", stylesFileBuilder.toCode())));

            Mx colorsFileBuilder = new Mx();
            colorsFileBuilder.a("colorPrimary", String.format("#%06X", colorPrimary & 0xffffff));
            colorsFileBuilder.a("colorPrimaryDark", String.format("#%06X", colorPrimaryDark & 0xffffff));
            colorsFileBuilder.a("colorAccent", String.format("#%06X", colorAccent & 0xffffff));
            colorsFileBuilder.a("colorControlHighlight", String.format("#%06X", colorControlHighlight & 0xffffff));
            colorsFileBuilder.a("colorControlNormal", String.format("#%06X", colorControlNormal & 0xffffff));
            srcCodeBeans.add(new SrcCodeBean("colors.xml",
                    CommandBlock.applyCommands("colors.xml", colorsFileBuilder.toCode())));
        }

        Mx stringsFileBuilder = new Mx();
        stringsFileBuilder.b("app_name", applicationName);
        srcCodeBeans.add(new SrcCodeBean("strings.xml",
                CommandBlock.applyCommands("strings.xml", stringsFileBuilder.toCode())));
        CommandBlock.x();
        return srcCodeBeans;
    }

    /**
     * Get generated source code of a file.
     *
     * @return The file's code or an empty String if not found
     */
    public String getFileSrc(String filename, hC projectFileManager, eC projectDataManager, iC projectLibraryManager) {
        a(projectLibraryManager, projectFileManager, projectDataManager, false);
        CommandBlock.x();
        boolean isJavaFile = filename.endsWith(".java");
        boolean isXmlFile = filename.endsWith(".xml");
        boolean isManifestFile = filename.equals("AndroidManifest.xml");
        ArrayList<ProjectFileBean> files = new ArrayList<>(projectFileManager.b());
        files.addAll(new ArrayList<>(projectFileManager.c()));

        if (isXmlFile) {
            /*
              Generating every java file is necessary to make command blocks for xml work
             */
            for (ProjectFileBean file : files) {
                CommandBlock.CBForXml(new Jx(N, file, projectDataManager).generateCode());
            }
        }

        if (isManifestFile) {
            Ix ix = new Ix(N, projectFileManager.b());
            ix.setYq(this);
            return CommandBlock.applyCommands("AndroidManifest.xml", ix.a());
        }

        for (ProjectFileBean file : files) {
            if (filename.equals(isJavaFile ? file.getJavaName() : file.getXmlName())) {
                if (isJavaFile) {
                    return new Jx(N, file, projectDataManager).generateCode();
                } else if (isXmlFile) {
                    Ox xmlGenerator = new Ox(N, file);
                    xmlGenerator.a(eC.a(projectDataManager.d(filename)), projectDataManager.h(filename));
                    return CommandBlock.applyCommands(filename, xmlGenerator.b());
                }
            }
        }

        return "";
    }

    /**
     * Calls {@link yq#a(hC, eC, iC, boolean)} with the same parameters and <code>false</code>.
     */
    public ArrayList<SrcCodeBean> a(hC hCVar, eC eCVar, iC iCVar) {
        return a(hCVar, eCVar, iCVar, false);
    }
}
