image:
  file: .gitpod.Dockerfile
  
tasks:
  - command: /opt/android-studio/bin/studio.sh
  - command: echo "Hello"
ports:
  - port: 5900
    onOpen: ignore
  - port: 6080
    onOpen: ignore
  - port: 35900
    onOpen: ignore
  - port: 6942
    onOpen: ignore